version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./database-schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  bot:
    build: .
    depends_on:
      - db
    environment:
      db_host: db
      db_user: ${db_user}
      db_pass: ${db_pass}
      db_name: ${db_name}
      db_port: 5432
      token: ${token}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
