name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - ci/cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_YANDEX_CLOUD_PRIVATE_KEY }}

    - name: Deploy to Yandex Cloud
      env:
        HOST: ${{ secrets.YANDEX_CLOUD_HOST }}
        USER: ${{ secrets.YANDEX_CLOUD_USER }}
      run: |
        run: |
        tar czf bot.tar.gz .
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bot.tar.gz ${{ env.USER }}@${{ env.HOST }}:/home/alechh/app/personal-drive-bot
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.USER }}@${{ env.HOST }} "cd /home/alechh/app/personal-drive-bot && tar xf bot.tar.gz && rm bot.tar.gz && docker-compose down && docker-compose up -d"