name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Pull and run Docker image
      run: |
        docker run --rm --name postgres-container -p 5432:5432 -e POSTGRES_USER=alechh -e POSTGRES_PASSWORD=123 -e POSTGRES_DB=postgres -d postgres:latest 
    
    - name: Install dependencies and run tests
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python3 -m pytest