name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Pull and run Docker image
      run: |
        docker build -t postgres-image ./database-schema 
        docker run --rm --name postgres-container -e db_user=alechh -e db_pass=123 -e db_name=postgres -e db_port=5432 -p 5432:5432 -d postgres-image
        
    - name: Install dependencies and run tests
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python3 -m pytest